name: Deploy to EC2
# masterにpushされた時にjobを実行する
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
    # 保存したシークレットたちを環境変数に設定
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SAKURA_USER: ${{ secrets.SAKURA_USER }}
      SAKURA_HOST: ${{ secrets.SAKURA_HOST }}
    run: |
      echo "$SECRET_KEY" > secret_key
      chmod 600 secret_key
      ssh -oStrictHostKeyChecking=no ${SAKURA_USER}@${SAKURA_HOST} -i secret_key "cd ~/folicolle && git pull origin master"
