name: only master branch

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v1
      - name: ssh
        run: | #
        ssh kiwatchi@kiwatchi.sakura.ne.jp
        t53vpnfvte
        cd folicolle
        git pull origin master
